name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master  # Set this to your main branch name
  workflow_dispatch: # Allow manual triggering

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
      
      # Debug step to check directory structure  
      - name: Debug directory structure
        run: |
          ls -la
          ls -la .next || echo ".next directory does not exist"
          ls -la .next/standalone || echo ".next/standalone directory does not exist"
        
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: miracademy
          directory: .next
          # Remove gitHubToken to avoid using GitHub deployments entirely
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Cloudflare Purge Cache
        if: success()
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }} 